from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
	url(r'^munchndrank/home$', 'munchndrank.views.home', name='home'),
	url(r'^$', 'django.contrib.auth.views.login', {'template_name':'yum/login.html'}),
    # route for built-in authentication with our own custom login page
    url(r'^munchndrank/login$', 'django.contrib.auth.views.login', {'template_name':'yum/login.html'}, name='login'),
    # route to logout a user and send them back to the login page
    url(r'^munchndrank/logout$', 'django.contrib.auth.views.logout_then_login', name='logout'),
    url(r'^munchndrank/register$', 'munchndrank.views_registration.register', name='register'),
    url(r'^confirm-registration/(?P<username>[a-zA-Z0-9_@\+\-]+)/(?P<token>[a-z0-9\-]+)$', 'munchndrank.views_registration.confirm_registration', name='confirm'),
    url(r'^munchndrank/user-settings/$', 'django.contrib.auth.views.password_change', {'template_name': 'yum/userSettings.html'}, name='user-settings'),
    url(r'^munchndrank/confirmed-password/$', 'django.contrib.auth.views.password_change_done', {'template_name': 'yum/confirmed_password.html'}, name='confirmed-password'),
    url(r'^munchndrank/userprofile$', 'munchndrank.views_profile.ownprofile_info', name='ownprofile'),
    url(r'^munchndrank/photo$', 'munchndrank.views_profile.get_photo', name='photo'),
    url(r'^munchndrank/edit-profile$', 'munchndrank.views_profile.edit_profile', name='editprofile'),
    url(r'^munchndrank/top-recipe$', 'munchndrank.views.top_recipe'),
    url(r'^munchndrank/addstream$', 'munchndrank.views.add_stream_page'),
    url(r'^munchndrank/followstream$', 'munchndrank.views.follow_stream'),
    url(r'^munchndrank/searchstream$', 'munchndrank.views.search_stream'),
    url(r'^munchndrank/foodstream$', 'munchndrank.views.foodstream', name='foodstream'),
    url(r'^munchndrank/drinkstream$', 'munchndrank.views.drinkstream', name='drinkstream'),
    url(r'^munchndrank/searchbyname$', 'munchndrank.views.search_by_name'),
    url(r'^munchndrank/searchbyfood$', 'munchndrank.views.search_by_food'),
    url(r'^munchndrank/recipe-editor$', 'munchndrank.views.show_recipe_editor'),
    url(r'^munchndrank/recipepic$', 'munchndrank.views.recipepic', name='recipepic'),
    url(r'^munchndrank/recipe-photo$', 'munchndrank.views.recipe_photo', name='recipephoto'),
    url(r'^munchndrank/post-recipe$','munchndrank.views.post_recipe'),
    url(r'^munchndrank/recipe/(?P<id>\d+)$', 'munchndrank.views.recipe'),
    url(r'^munchndrank/edit-recipe/(?P<id>\d+)$', 'munchndrank.views.edit'),
    url(r'^munchndrank/changerecipe-photo/(?P<id>\d+)$', 'munchndrank.views.changerecipe_photo', name='changerecipephoto'),
    url(r'^munchndrank/suggestion/(?P<id>\d+)$', 'munchndrank.views.suggestion'),
    url(r'^munchndrank/save-edit$', 'munchndrank.views.save_edit'),
    url(r'^munchndrank/recipephoto/(?P<id>\d+)$', 'munchndrank.views.get_recipe_photo', name='get_recipephoto'),
    url(r'^munchndrank/recipebook$', 'munchndrank.views.recipebook'),
    url(r'^munchndrank/openbook/(?P<user>[a-zA-Z0-9_@\+\-]+)$', 'munchndrank.views.show_openbook'),
    url(r'^munchndrank/profile/(?P<user>[a-zA-Z0-9_@\+\-]+)$', 'munchndrank.views_profile.profile'),
    url(r'^munchndrank/userphoto/(?P<user>[a-zA-Z0-9_@\+\-]+)$', 'munchndrank.views_profile.get_prof_photo', name='userphoto'),
    url(r'^munchndrank/save-recipe/(?P<id>\d+)$', 'munchndrank.views.save_recipe'),
    url(r'^munchndrank/nearest-food$', 'munchndrank.views.find_nearest_food'),
    url(r'^munchndrank/delete-recipe/(?P<id>\d+)$', 'munchndrank.views.delete_recipe'),
    url(r'^munchndrank/update-rating', 'munchndrank.views.update_rating'),
    # password email reset
    url(r'^munchndrank/password_reset/$', 
        'django.contrib.auth.views.password_reset', 
        {'post_reset_redirect' : '/munchndrank/password_reset_done/'},
        name="password_reset"),
    (r'^munchndrank/password_reset_done/$',
        'django.contrib.auth.views.password_reset_done'),
    (r'^munchndrank/password_reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 
        'django.contrib.auth.views.password_reset_confirm', 
        {'post_reset_redirect' : '/munchndrank/password_done/'}),
    (r'^munchndrank/password_done/$', 
        'django.contrib.auth.views.password_reset_complete'),
)
